language: node_js

node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
  - "3"
  - "2"
  - "1"
  - "0.12"
  - "0.10"
  - "0.8"
  - "0.6"

before_script:
  - npm install

script:
  - npm test
